#!/bin/sh
/homes/lesh/java/jdk1.3/bin/java -classpath "/homes/lesh/java/" hugs.apps.crossing.Crossing -noAutoStart -loadProblem /homes/lesh/java/hugsSandbox/problems/demo.crossing.prb -loadSolution /homes/lesh/java/hugsSandbox/solutions/demo.crossing.sol $0 $1 $2 $3 $4 $5 $6 $7 $8 $9
